[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_port = /dev/tty.usbserial-14320
monitor_filters = esp32_exception_decoder
upload_port = /dev/tty.usbserial-14320
;upload_speed = 921000

; Partition options:
;board_build.partitions = default.csv    ; app ~1.3MB + OTA
; board_build.partitions = no_ota.csv     ; larger single app, no OTA
board_build.partitions = min_spiffs.csv ; app + small SPIFFS
;board_build.partitions = huge_app.csv     ; max app size, no OTA (active)

; WARNING There are two scripts used. 
; The first one is used to generate the lv_conf.h file based on the settings in the platformio.ini file. 
; One the last version of CYD board (wuth USB-C) the #define TFT_INVERSION_ON must be uncommented in the User_Setup.h file, otherwise the display will be inverted. This is a known issue with the current version of the 
; TFT_eSPI library and the CYD board. The generated lv_conf.h file will include the TFT_INVERSION_ON definition if it is uncommented in the User_Setup.h file.
; The second one is used to generate the FrameWeb.cpp file based on the FrameWeb.html file. The second script is called after the first one, so that the generated lv_conf.h file can be included in the FrameWeb.cpp file.
extra_scripts = pre:prebuild.py,  pre:.pio/libdeps/esp32dev/Esp32_Framework/extra_script.py
custom_in_html = .pio/libdeps/esp32dev/Esp32_Framework/src/FrameWeb.html
custom_out_h = .pio/libdeps/esp32dev/Esp32_Framework/src/FrameWeb.cpp
custom_out_zip = zib

lib_deps = 
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	bodmer/TFT_eSPI@^2.5.43
	lvgl/lvgl@^9.2.2
	https://github.com/beegee-tokyo/DHTesp.git
	; WebFramework and dependencies
  https://github.com/tzapu/WiFiManager.git#master
  https://github.com/Links2004/arduinoWebSockets#master
  DNSServer
  WebServer
  ArduinoJson
	https://github.com/dupuyb/Esp32_Framework.git

build_flags = 
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM											# PSRAM mod used - no RGB LED
	-mfix-esp32-psram-cache-issue					#
 	-mfix-esp32-psram-cache-strategy=memw	#
	-DUSE_BACKLIGHT_MOD										# TFT fixed backlight mod used, will free up the GPIO21
	-DAUDIO_LOG 													# enable log info in the audio library
	-DLV_CONF_INCLUDE_SIMPLE
  ;-D LOG_FRAMEWEB_ENABLED             # Enable debug output for FrameWeb (prefix [F])


build_src_filter = +<*> 
   -<.git/> 
   -<.svn/> 
   -<.pio/libdeps/esp32dev/Esp32_Framework/src/examples/*> ; exclude example demo*.cpp files

[platformio]
description = ESP32 CYD Pid Controller
